### PR TITLE
Set correct execution permission.

### PR DESCRIPTION
**Pull request by lf94**
For hacktoberfest...Not much but I'm short on time.

Another request is coming for the $EDITOR feature.

### CODE REVIEW

**Comment by 0mp** [comment]
That's super cool. I'll look into this PR in a few days! Sorry for the delay!

**Comment by lf94** [comment]
I dont think it counts towards Hacktoberfest if you don't merge it before the 31st...!

**Comment by 0mp** [comment]
@lf94 I'm sure it does. Read the rules carefully :) Your tshirt is safe!

> To get a shirt, you must make four pull requests between October 1-31. Pull requests can be to any public repo on GitHub, not just the ones we've highlighted. Pull requests reported by maintainers as spam or that are automated will be marked as invalid and won’t count towards the shirt.

https://hacktoberfest.digitalocean.com

Thanks a lot for contributing!

**Comment by lf94** [comment]
Ah nice! I actually just got their email. Great.

I'm glad I discovered goat though...this is something I've been looking for. I always have a particular project I'm working on and being able to type "goat myRecentProject" is really helpful. Keep it up!

**Comment by khamer** [comment]
Hey @lf94, I didn't see your comments here and did a pass at the `$EDITOR` PR as well.

That said, +1 on getting the correct execute permission on goat.sh - definitely a fix worth adding.

**Comment by 0mp** [comment]
Actually, I do not understand why it is a good idea to set x permissions on goat.sh. goat.sh itself is not a script you would like to run as a command. It called with `sh` in goat-agent.sh which is generated by goat-keeper.sh. goat-keeper.sh is in fact the only piece of code you want to run as a command in shortcut managing _framework_.

When it comes to the editor feature  - it simply does not work. Have you tested it before submitting a PR?

I am going to close this PR for the time being - ping me if you decide to fix it.

**Pull request closed without merging**
